apiVersion: v1
kind: ReplicationController
metadata:
 name: nginx
spec:
 replicas: 3
 template:
   metadata:
     labels:
       run: nginx
   spec:
     containers:
     - name: nginx
       image: nginx
       ports:
       - containerPort: 80
