apiVersion: v1
kind: Pod
metadata:
 name: ubuntuapp
 #annotations:
 #  "opencontrail.org/network" : '{"domain":"default-domain", "project": "admin", "name": "openstack-vn"}'
 labels:
   app: ubuntuapp
spec:
 containers:
   - name: ubuntuapp
     image: ubuntu-upstart
