---
- name: address resolution
  hosts: all
  sudo: yes
  tasks:
    - command: /sbin/route delete -net 0.0.0.0/0 dev eth0
    - command: /sbin/route add -net 0.0.0.0/0 gw 10.13.82.1
    - command: /sbin/route add -net 192.168.2.0/24 gw 192.168.1.1
    - command: /sbin/route add -net 10.10.10.0/24 gw 192.168.1.1
    - command: /sbin/route add -net 192.168.254.0/24 gw 192.168.1.1
